learning_rate:
  name    : learning_rate
  type    : float
  choices : 
  low     : 1e-6
  high    : 1e-4
  step    :
  log     : True

gen_drop_rate:
  name    : gen_drop_rate
  type    : float
  choices : 
  low     : 0.5
  high    : 1.
  step    :
  log     : False

disc_drop_rate:
  name    : disc_drop_rate
  type    : float
  choices : 
  low     : 0.5
  high    : 1.
  step    :
  log     : False
  
batch_size:
  name    : batch_size
  type    : int
  choices : 
  low     : 1
  high    : 1e4
  step    :
  log     : True
